### ISSUE TITLE
Update database schema 0.2.7 => 0.3

### ISSUE THREAD

**Issue by ToeiRei** [kiswa/TaskBoard#200]
Hi guys,

I upgraded from 0.2.7 to 0.3 and finally got stuck with the following error hidden at the JS console:

```
Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 8
Message: Undefined offset: 0
File: /home/kanban/public_html/api/userRoutes.php
Line: 143
Trace

#0 /home/kanban/public_html/api/userRoutes.php(143): Slim\Slim::handleErrors(8, 'Undefined offse...', '/home/kanban/pu...', 143, Array)
#1 [internal function]: {closure}()
#2 /home/kanban/public_html/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#3 /home/kanban/public_html/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#4 /home/kanban/public_html/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#5 /home/kanban/public_html/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#6 /home/kanban/public_html/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 /home/kanban/public_html/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#8 /home/kanban/public_html/api/api.php(51): Slim\Slim->run()
#9 {main}
```

Any ideas on how to combat that one?

Cheers
Rei

**Comment by ToeiRei** [comment]
I guess I have a hackish workaround here. Not nice, but works for me (tm)

Around line 142-146, the $options are triggering the undefined index error. So I guess I am just missing a few settings in my user profile there.

Changed 
```
 $options = [
```
to
```
 @$options = [
```

to work around that for now. But I'd be happy if someone could look over my solution and maybe do an official and proper fix.

**Comment by ToeiRei** [comment]
In fact, it was the 'options' table which caused the error. As a temp. resolution:

Open the taskboard.db file with an sqlite editor and fire the following queries:

```
CREATE TABLE `option` ( `id` INTEGER PRIMARY KEY AUTOINCREMENT  ,`tasks_order` INTEGER,`show_animations` INTEGER,`show_assignee` INTEGER,`user_id` INTEGER  , FOREIGN KEY(`user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE SET NULL )
```

and per user you got, insert the options. Careful, user_id needs to map to existing users (as seen in the users table)

```
insert into option ("id", "tasks_order", "show_animations", "show_assignee", "user_id") values ('1', '0', '0', '0', '1');
insert into option ("id", "tasks_order", "show_animations", "show_assignee", "user_id") values ('2', '0', '0', '0', '2');
insert into option ("id", "tasks_order", "show_animations", "show_assignee", "user_id") values ('3', '0', '0', '0', '3');
....
````

**Comment by kiswa** [comment]
Thanks for figuring this out. I should have tested upgrading from 0.2.7 to 0.3.0 since I added a new table.

In the future I'll provide upgrade scripts if needed!
