### ISSUE TITLE
Unhandled Error when building re-write

### ISSUE THREAD

**Issue by aheinricy** [kiswa/TaskBoard#421]
I'm trying to setup re-write branch and running into an error when running gulp. I've made sure the api directory is writeable and I'm still getting the following error. 

/opt/TaskBoard# gulp
[16:22:56] Using gulpfile /opt/TaskBoard/gulpfile.js
[16:22:56] Starting 'vendor'...
[16:22:56] Starting 'ts-lint'...
[16:22:56] Starting 'tsc'...
[16:22:56] Starting 'html'...
[16:22:56] Starting 'json'...
[16:22:56] Starting 'images'...
[16:22:56] Starting 'scss-lint'...
[16:22:56] Starting 'fonts'...
[16:22:56] Starting 'scss'...
[16:22:56] Starting 'api'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /opt/TaskBoard/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by kiswa** [comment]
Looks like an error installing dependencies. Give `npm i` another run and make sure everything installs.

**Comment by aheinricy** [comment]
I figured it out. I had an older version of nodejs and it wasn't compatible. I upgrade nodjs and it resolved my error. Thanks for the hint on what to look for.
