### ISSUE TITLE
Illegal string offset in get_all_headers() on PHP >= 7

### ISSUE THREAD

**Issue by gruentee** [kiswa/TaskBoard#448]
`get_all_headers()` in `helper.php` throws an Illegal string offset error.
Running PHP 7.2.11

```
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "ErrorException: Illegal string offset 'Accept-Language' in /srv/http/taskboard.dynv6.n
et/api/helpers.php:11"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "Stack trace:"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#0 /srv/http/example.com/api/helpers.php(11): Slim\Slim::handleErrors(2, 'Ille
gal string ...', '/srv/http/taskb...', 11, Array)"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#1 /srv/http/example.com/api/helpers.php(53): getallheaders()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#2 /srv/http/example.com/api/helpers.php(328): getUser()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#3 /srv/http/example.com/api/helpers.php(306): checkDbToken()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#4 /srv/http/example.com/api/boardRoutes.php(117): validateToken()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#5 [internal function]: {closure}()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#6 /srv/http/example.com/vendor/slim/slim/Slim/Route.php(468): call_user_func_
array(Object(Closure), Array)"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#7 /srv/http/example.com/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#8 /srv/http/example.com/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#9 /srv/http/example.com/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#10 /srv/http/example.com/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#11 /srv/http/example.com/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#12 /srv/http/example.com/api/api.php(52): Slim\Slim->run()"
[01-Nov-2018 14:43:08] WARNING: [pool www] child 9721 said into stderr: "#13 {main}"
```

Caused by assigning an declaring and assigning values to a variable (array) previously declared as string.

**Comment by bbichero** [comment]
What branch of Taskboard are you running ?
Only the `re-write` support php 7.
Can you provide us more information about your environment ?
What distribution are you running ? (execute `cat /etc/*release`)
Which step have you done to install  php and taskboard ?
Thanks.

**Comment by gruentee** [comment]
> Only the re-write support php 7.
Alright, I wasnt aware of this. 

Closing.'
