### ISSUE TITLE
freeze when login

### ISSUE THREAD

**Issue by adeljaffan** [kiswa/TaskBoard#606]
when i upload this project on local server , the website freeze when i enter username and password with no message error, the color of sign in button changed !

**Comment by Berational91** [comment]
You have to turn on the mod_rewrite/RewriteEngine in the configuration of your Webserver

**Comment by jkrische** [comment]
Same issue.  Mod rewrite is already on.  Any other suggestions?

looked at the Network console, there's some 404 errors for things not found:

before login, cannot find:
/api/authenticate

After login, cannot find:
/api/login

**Comment by dwagnereh** [comment]
I have same issue and getting this in the chrome console:
{"notify":"init_tab"}
zone.js:3324          POST http://srvteampass1.essehealth.com/TaskBoard1/api/authenticate 404 (Not Found)
k @ zone.js:3324
e.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:294
e.scheduleTask @ zone.js:400
t.scheduleTask @ zone.js:231
t.scheduleMacroTask @ zone.js:254
s @ zone.js:1183
(anonymous) @ zone.js:3357
T.o.<computed> @ zone.js:1501
(anonymous) @ http.js:1776
_zoneSubscribe @ zone-patch-rxjs.js:76
value @ Observable.js:42
value @ Observable.js:28
value @ tap.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
h @ innerSubscribe.js:67
value @ mergeMap.js:57
value @ mergeMap.js:51
value @ mergeMap.js:34
value @ Subscriber.js:49
Zone.__load_patch.e.Subscriber.next @ zone-patch-rxjs.js:163
(anonymous) @ subscribeToArray.js:3
_zoneSubscribe @ zone-patch-rxjs.js:76
value @ Observable.js:42
value @ Observable.js:28
value @ mergeMap.js:19
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ filter.js:13
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ map.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ map.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ catchError.js:14
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
t.ngOnInit @ login.component.ts:32
sn @ core.js:3038
an @ core.js:3008
rn @ core.js:2960
li @ core.js:7186
(anonymous) @ core.js:8279
li @ core.js:7195
Ri @ core.js:8325
(anonymous) @ core.js:6964
li @ core.js:7221
hi @ core.js:7285
(anonymous) @ core.js:8497
Fi @ core.js:8522
value @ core.js:9898
value @ core.js:28350
(anonymous) @ core.js:28239
e.invoke @ zone.js:386
onInvoke @ core.js:27436
e.invoke @ zone.js:385
t.run @ zone.js:143
value @ core.js:27318
next @ core.js:28238
a @ core.js:24800
value @ Subscriber.js:183
value @ Subscriber.js:122
value @ Subscriber.js:72
value @ Subscriber.js:49
Zone.__load_patch.e.Subscriber.next @ zone-patch-rxjs.js:163
value @ Subject.js:39
value @ core.js:24790
gc @ core.js:27372
onHasTask @ core.js:27450
e.hasTask @ zone.js:441
e._updateTaskCount @ zone.js:462
t._updateTaskCount @ zone.js:284
t.runTask @ zone.js:205
g @ zone.js:601
Promise.then (async)
y @ zone.js:584
e.scheduleTask @ zone.js:410
t.scheduleTask @ zone.js:231
t.scheduleMicroTask @ zone.js:251
w @ zone.js:881
e.then @ zone.js:1027
value @ core.js:28024
zUnb @ main.ts:11
l @ bootstrap:79
0 @ main.js:1
l @ bootstrap:79
t @ bootstrap:45
r @ bootstrap:32
(anonymous) @ main.js:1
zone.js:3324          POST http://srvteampass1.essehealth.com/TaskBoard1/api/login 404 (Not Found)
k @ zone.js:3324
e.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:294
e.scheduleTask @ zone.js:400
t.scheduleTask @ zone.js:231
t.scheduleMacroTask @ zone.js:254
s @ zone.js:1183
(anonymous) @ zone.js:3357
T.o.<computed> @ zone.js:1501
(anonymous) @ http.js:1776
_zoneSubscribe @ zone-patch-rxjs.js:76
value @ Observable.js:42
value @ Observable.js:28
value @ tap.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
h @ innerSubscribe.js:67
value @ mergeMap.js:57
value @ mergeMap.js:51
value @ mergeMap.js:34
value @ Subscriber.js:49
Zone.__load_patch.e.Subscriber.next @ zone-patch-rxjs.js:163
(anonymous) @ subscribeToArray.js:3
_zoneSubscribe @ zone-patch-rxjs.js:76
value @ Observable.js:42
value @ Observable.js:28
value @ mergeMap.js:19
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ filter.js:13
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ map.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ map.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ catchError.js:14
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
t.login @ login.component.ts:50
(anonymous) @ login.component.html:11
wa @ core.js:14315
i @ core.js:14350
(anonymous) @ platform-browser.js:582
e.invokeTask @ zone.js:421
onInvokeTask @ core.js:27424
e.invokeTask @ zone.js:420
t.runTask @ zone.js:188
t.invokeTask @ zone.js:503
h @ zone.js:1671
p @ zone.js:1697
core.js:4197 ERROR TypeError: Cannot read properties of undefined (reading 'forEach')
    at n._next (login.component.ts:51:23)
    at n.value (Subscriber.js:183:16)
    at n.value (Subscriber.js:122:22)
    at n.value (Subscriber.js:72:26)
    at n.value (Subscriber.js:49:18)
    at Zone.__load_patch.e.Subscriber.next (zone-patch-rxjs.js:163:33)
    at n.value (innerSubscribe.js:42:26)
    at n.value (innerSubscribe.js:10:21)
    at n.value (Subscriber.js:49:18)
    at Zone.__load_patch.e.Subscriber.next (zone-patch-rxjs.js:163:33)
qn @ core.js:4197
value @ core.js:4245
next @ core.js:27987
a @ core.js:24800
value @ Subscriber.js:183
value @ Subscriber.js:122
value @ Subscriber.js:72
value @ Subscriber.js:49
Zone.__load_patch.e.Subscriber.next @ zone-patch-rxjs.js:163
value @ Subject.js:39
value @ core.js:24790
(anonymous) @ core.js:27459
e.invoke @ zone.js:386
t.run @ zone.js:143
value @ core.js:27363
onHandleError @ core.js:27459
e.handleError @ zone.js:390
t.runTask @ zone.js:191
t.invokeTask @ zone.js:503
invoke @ zone.js:492
n.args.<computed> @ zone.js:3034
setTimeout (async)
c @ zone.js:3055
e.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:294
e.scheduleTask @ zone.js:400
t.scheduleTask @ zone.js:231
t.scheduleMacroTask @ zone.js:254
s @ zone.js:1183
(anonymous) @ zone.js:3068
T.o.<computed> @ zone.js:1501
r @ hostReportError.js:2
value @ Subscriber.js:191
value @ Subscriber.js:122
value @ Subscriber.js:72
value @ Subscriber.js:49
Zone.__load_patch.e.Subscriber.next @ zone-patch-rxjs.js:163
value @ innerSubscribe.js:42
value @ innerSubscribe.js:10
value @ Subscriber.js:49
Zone.__load_patch.e.Subscriber.next @ zone-patch-rxjs.js:163
(anonymous) @ subscribeToArray.js:3
_zoneSubscribe @ zone-patch-rxjs.js:76
value @ Observable.js:42
value @ Observable.js:28
h @ innerSubscribe.js:67
value @ catchError.js:36
value @ Subscriber.js:75
value @ Subscriber.js:55
Zone.__load_patch.e.Subscriber.error @ zone-patch-rxjs.js:175
value @ Subscriber.js:75
value @ Subscriber.js:55
Zone.__load_patch.e.Subscriber.error @ zone-patch-rxjs.js:175
value @ Subscriber.js:75
value @ Subscriber.js:55
Zone.__load_patch.e.Subscriber.error @ zone-patch-rxjs.js:175
value @ innerSubscribe.js:45
value @ innerSubscribe.js:13
value @ Subscriber.js:55
Zone.__load_patch.e.Subscriber.error @ zone-patch-rxjs.js:175
value @ tap.js:56
value @ Subscriber.js:55
Zone.__load_patch.e.Subscriber.error @ zone-patch-rxjs.js:175
c @ http.js:1691
e.invokeTask @ zone.js:421
onInvokeTask @ core.js:27424
e.invokeTask @ zone.js:420
t.runTask @ zone.js:188
t.invokeTask @ zone.js:503
h @ zone.js:1671
p @ zone.js:1708
load (async)
x @ zone.js:1823
e.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:294
e.scheduleTask @ zone.js:400
t.scheduleTask @ zone.js:231
t.scheduleEventTask @ zone.js:257
(anonymous) @ zone.js:1980
(anonymous) @ http.js:1764
_zoneSubscribe @ zone-patch-rxjs.js:76
value @ Observable.js:42
value @ Observable.js:28
value @ tap.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
h @ innerSubscribe.js:67
value @ mergeMap.js:57
value @ mergeMap.js:51
value @ mergeMap.js:34
value @ Subscriber.js:49
Zone.__load_patch.e.Subscriber.next @ zone-patch-rxjs.js:163
(anonymous) @ subscribeToArray.js:3
_zoneSubscribe @ zone-patch-rxjs.js:76
value @ Observable.js:42
value @ Observable.js:28
value @ mergeMap.js:19
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ filter.js:13
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ map.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ map.js:16
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
value @ catchError.js:14
(anonymous) @ zone-patch-rxjs.js:104
T.o.<computed> @ zone.js:1501
value @ Observable.js:23
t.login @ login.component.ts:50
(anonymous) @ login.component.html:11
wa @ core.js:14315
i @ core.js:14350
(anonymous) @ platform-browser.js:582
e.invokeTask @ zone.js:421
onInvokeTask @ core.js:27424
e.invokeTask @ zone.js:420
t.runTask @ zone.js:188
t.invokeTask @ zone.js:503
h @ zone.js:1671
p @ zone.js:1697

**Comment by jbakuwel** [comment]
Did you add AllowOverride in your apache config? Example:

        <Directory /var/www/projects.example.com>
                Options Indexes FollowSymLinks
                AllowOverride all
                Require all granted
        </Directory>

**Comment by suquetpaul** [comment]
I'm having the same issue here. Interestingly, not even the demo in the official page runs. It behaves exactly the same. Thinking there might be a limitation from my ISP or a firewall, tried in 3 different networks already, all from different providers. No luck. Tested 2 different Windows 11 and Windows 10 machines, as well as a phone on Android 13 and a tablet on Android 6. All having the same results.
